"""add source-reported novel statistics

Revision ID: 41a15d44d6fc
Revises: 064c024aa744
Create Date: 2026-09-25 17:22:16.408461
"""

from typing import Sequence, Union

from alembic import op
import sqlmodel as sa
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "41a15d44d6fc"
down_revision: Union[str, Sequence[str], None] = "064c024aa744"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

try:
    dialect = op.get_context().dialect.name
except Exception:
    dialect = ""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("novels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_id", AutoString(), nullable=True))
        batch_op.add_column(sa.Column("word_count", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("total_recommendations", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("weekly_recommendations", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("weekly_tipper_count", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("source_chapter_count", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("author_work_count", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("author_level", AutoString(), nullable=True))
        batch_op.add_column(sa.Column("author_total_word_count", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("author_creation_days", sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("novels", schema=None) as batch_op:
        batch_op.drop_column("author_creation_days")
        batch_op.drop_column("author_total_word_count")
        batch_op.drop_column("author_level")
        batch_op.drop_column("author_work_count")
        batch_op.drop_column("source_chapter_count")
        batch_op.drop_column("weekly_tipper_count")
        batch_op.drop_column("weekly_recommendations")
        batch_op.drop_column("total_recommendations")
        batch_op.drop_column("word_count")
        batch_op.drop_column("source_id")

    # ### end Alembic commands ###
