"""add novel ranking names

Revision ID: f305154db667
Revises: 41a15d44d6fc
Create Date: 2026-09-25 18:32:51.275313
"""

from typing import Sequence, Union

from alembic import op
import sqlmodel as sa

# revision identifiers, used by Alembic.
revision: str = "f305154db667"
down_revision: Union[str, Sequence[str], None] = "41a15d44d6fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

try:
    dialect = op.get_context().dialect.name
except Exception:
    dialect = ""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("novels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ranking_names", sa.JSON(), nullable=False, server_default="[]")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("novels", schema=None) as batch_op:
        batch_op.drop_column("ranking_names")

    # ### end Alembic commands ###
